version: "3.5"
services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        networks:
          - no-internet 
        expose:
          - 5432
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=db

    mysql:
        image: mysql:latest
        restart: unless-stopped
        networks:
          - no-internet 
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=mysql

    # The oracle database may take longer to start.
    # $> sqlplus system/oracle@oracle:1521/xe_pdb1
    oracle:
      image: gvenzl/oracle-xe:latest
      restart: unless-stopped
      networks:
        - no-internet
      ports: 
        - "1521:1521"
      expose:
        - 1521  # Oracle SQL*Net port
      environment:
        - ORACLE_PASSWORD=oracle  # Password for SYS and SYSTEM
        - ORACLE_DATABASE=xe_pdb1  # Name of the new pluggable database
        # Uncomment this and modify butterfly service and init.sh to use a non-system user
        # WARN: Non system users do not have access to functions like `dbms_pipe.receive_message(('a'),10) ` by default
        # - APP_USER=oracle  # Name of the new database schema user
        # - APP_USER_PASSWORD=oracle  # Password for the new database schema user

    mssql:
      image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
      restart: unless-stopped
      networks:
        - no-internet
      ports:
        - "1433:1433"
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=EJAZHEJZAHJEZ2193939219312@@@@dzadazd # Strong password is required, so I smashed my head on the keyboard
        - MSSQL_PID=Evaluation

    db2:
      image: ibmcom/db2
      restart: unless-stopped

      networks:
        - no-internet
      privileged: true
      ports:
        - "50000:50000"
      expose:
        - 50000
      environment:
        - LICENSE=accept
        - DB2INST1_PASSWORD=VeryStr0ngP@ssword
        - DBNAME=testdb

    butterfly:
        image: our_butterfly
        build: .
        restart: unless-stopped
        networks:
          - no-internet 
        expose:
          - 8881
          - 8882
          - 8883
          - 8884
          - 8885
          - 8886
        environment:
          - PGPASSWORD=postgres
          - PGHOST=postgres
          - PGPORT=5432
          - PGUSER=postgres
          - PGDATABASE=db 
          - MYSQL_HOST=mysql
          - MYSQL_PWD=mysql
          - MYSQL_TCP_PORT=3306
          - USER=root
          - ORACLE_HOST=oracle
          - ORACLE_PORT=1521
          - ORACLE_USER=system
          # - ORACLE_USER=oracle
          - ORACLE_PASSWORD=oracle
          - ORACLE_PDB=xe_pdb1
          - MSSQL_HOST=mssql
          - SA_PASSWORD=EJAZHEJZAHJEZ2193939219312@@@@dzadazd
          - DB2_HOST=db2
          - DB2_USER=db2inst1
          - DB2_PASSWORD=VeryStr0ngP@ssword
          - DB2_DATABASE=testdb



    proxy:
        image: nginx
        volumes:
            - ./proxy/templates:/etc/nginx/templates
            - ./proxy/content:/usr/share/nginx/html:ro
        ports:
            - "8888:80"
        restart: always
        networks:
          - no-internet 
          - internet
        depends_on: [butterfly]

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
