version: "3.5"
services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        networks:
          - no-internet 
        expose:
          - 5432
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=db

    mysql:
        image: mysql:latest
        restart: unless-stopped
        networks:
          - no-internet 
        expose:
          - 3306
        environment:
          - MYSQL_ROOT_PASSWORD=mysql

    # The oracle database may take longer to start.
    # $> sqlplus oracle/oracle@oracle:1521/xe_pdb1
    oracle:
      image: gvenzl/oracle-xe:latest
      restart: unless-stopped
      networks:
        - no-internet
      ports: 
        - "1521:1521"
      expose:
        - 1521  # Oracle SQL*Net port
      environment:
        - ORACLE_PASSWORD=oracle  # Password for SYS and SYSTEM
        - ORACLE_DATABASE=xe_pdb1  # Name of the new pluggable database
        # Uncomment this and modify butterfly service and init.sh to use a non-system user
        # - APP_USER=oracle  # Name of the new database schema user
        # - APP_USER_PASSWORD=oracle  # Password for the new database schema user


    butterfly:
        image: our_butterfly
        build: .
        restart: unless-stopped
        networks:
          - no-internet 
        expose:
          - 8881
          - 8882
          - 8883
          - 8884
        environment:
          - PGPASSWORD=postgres
          - PGHOST=postgres
          - PGPORT=5432
          - PGUSER=postgres
          - PGDATABASE=db 
          - MYSQL_HOST=mysql
          - MYSQL_PWD=mysql
          - MYSQL_TCP_PORT=3306
          - USER=root
          - ORACLE_HOST=oracle
          - ORACLE_PORT=1521
          - ORACLE_USER=system
          # - ORACLE_USER=oracle
          - ORACLE_PASSWORD=oracle
          - ORACLE_PDB=xe_pdb1


    proxy:
        image: nginx
        volumes:
            - ./proxy/templates:/etc/nginx/templates
            - ./proxy/content:/usr/share/nginx/html:ro
        ports:
            - "8888:80"
        restart: always
        networks:
          - no-internet 
          - internet
        depends_on: [butterfly]

networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
